
/**
 * CANONICAL EVENT REGISTRY
 * 
 * Every interaction within the platform must be represented here.
 * This registry ensures type safety across the event bus.
 */

export enum NexusEvent {
  // SENSORY (Services -> Event Pipeline)
  MARKET_DATA_RECEIVED = 'MARKET_DATA_RECEIVED',
  EXCHANGE_CONNECTED = 'EXCHANGE_CONNECTED',
  EXCHANGE_DISCONNECTED = 'EXCHANGE_DISCONNECTED',

  // COGNITIVE (Analysis -> Event Pipeline)
  SIGNAL_GENERATED = 'SIGNAL_GENERATED',
  SIGNAL_REJECTED = 'SIGNAL_REJECTED',
  
  // REGULATORY (Risk -> Event Pipeline)
  RISK_CHECK_PASSED = 'RISK_CHECK_PASSED',
  RISK_CHECK_FAILED = 'RISK_CHECK_FAILED',
  KILL_SWITCH_TRIGGERED = 'KILL_SWITCH_TRIGGERED',

  // OPERATIONAL (Internal Transitions)
  PULSE_TICK = 'PULSE_TICK',
  STATE_TRANSITION = 'STATE_TRANSITION',
  MEMORY_SNAPSHOT = 'MEMORY_SNAPSHOT',
  
  // COMMAND (User -> Event Pipeline)
  COMMAND_RECEIVED = 'COMMAND_RECEIVED',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',

  // EXECUTION (Event Pipeline -> Operations)
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_EXECUTED = 'ORDER_EXECUTED',
  ORDER_FAILED = 'ORDER_FAILED',

  // FAILURES
  FATAL_FAILURE = 'FATAL_FAILURE',
  RECOVERABLE_FAILURE = 'RECOVERABLE_FAILURE',
  DEGRADED_FAILURE = 'DEGRADED_FAILURE',

  // SYSTEM
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  AUDIT_LOG = 'AUDIT_LOG',
  SYSTEM_INIT = 'SYSTEM_INIT',
  SNAPSHOT_RESTORE = 'SNAPSHOT_RESTORE',
  ROLLBACK_COMPLETE = 'ROLLBACK_COMPLETE',
  MARKET_UPDATED = 'MARKET_UPDATED',
  REPLAY_STARTED = 'REPLAY_STARTED',
  REPLAY_COMPLETED = 'REPLAY_COMPLETED',
  HEARTBEAT_STALLED = 'HEARTBEAT_STALLED',
  HEARTBEAT_RESUMED = 'HEARTBEAT_RESUMED'
}

export interface NexusEventPayload {
  eventId: string;
  sequenceId: number;
  timestamp: number;
  type: NexusEvent;
  source: string;
  data: any;
  correlationId?: string;
  causationId?: string;
  version: string;
}
